apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: chaos-eater
  name: pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /chaos-eater