apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chaos-hunter
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-immediate
  resources:
    requests:
      storage: 1Gi