# k8s/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: chaos-hunter
  name: pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi