FROM docker:27.5.1-dind

RUN echo "Building docker in docker image"
ENV INSIDE_DOCKER=true

#------------------------
# install basic packages
#------------------------
RUN apk add bash
RUN apk add curl
RUN apk add dos2unix
# for envsubst in create_kind_cluster.sh
RUN apk add gettext 

#---------------------
# install environment
#---------------------
WORKDIR /app
COPY . .
RUN dos2unix ./create_environment.sh
RUN chmod +x ./create_environment.sh
RUN /bin/bash ./create_environment.sh

#----------------------------
# copy the entrypoint script
#----------------------------
COPY create_kind_cluster.sh /usr/local/bin/entrypoint.sh
RUN dos2unix /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh